#!/bin/bash
# This scripts starts and restarts, if necessary, the btu_meter.py program.
# Any arguments passed to this script are passed to the btu_meter program.
until /home/pi/pi-bear/bear_cam.py "$@"; do
    echo "Script 'bear_cam.py' crashed with exit code $?.  Respawning.." >&2
    sleep 2
done